services:
  app:
    build:
      context: .
    container_name: laravel-app
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      - ./my-laravel-app:/var/www  # プロジェクトのルートディレクトリをマウント
    networks:
      - app-network
    depends_on:
      - mariadb

  webserver:
    image: nginx:alpine
    container_name: nginx-webserver
    volumes:
      - ./my-laravel-app:/var/www  # プロジェクトのルートディレクトリをマウント
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"  # ここでホストの8080ポートをコンテナの80ポートにマッピング
    networks:
      - app-network
    depends_on:
      - app

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306" 
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network

  mail:
    image: mailhog/mailhog
    container_name: "mailhog"
    platform: linux/amd64  # ここでプラットフォームを指定
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
